Fix dedalo squid logs
NethServer/nethserver-dedalo pull request #10
Opened 2018-04-26 12:47 UTC by cotosso

nethserver/dev#5473

2018-05-02 12:13 UTC, gsanchietti requested changes

2018-05-02 12:13 UTC, gsanchietti commented on root/etc/e-smith/templates/etc/squid/squid.conf/20acl_50_dedalo
> -        $OUT .= "access_log daemon:/var/log/squid/access.log squid\n";
The meaning of this line is "log everything inside access.log", but now we want to change it to "log everything inside access.log, except traffic from dedalo network".

If possible, please change the implementation to a single line of configuration, removing all blue-related stuff.
This syntax should do the job:
```
access_log daemon:/var/log/squid/access.log squid !dedalo
```

See http://www.squid-cache.org/Doc/config/acl/

2018-05-10 16:14 UTC, cotosso commented on root/etc/e-smith/templates/etc/squid/squid.conf/20acl_50_dedalo
> -        $OUT .= "access_log daemon:/var/log/squid/access.log squid\n";
I just tried your change proposal and it worked perfectly.

2018-05-11 10:16 UTC, gsanchietti commented on root/etc/e-smith/templates/etc/squid/squid.conf/20acl_50_dedalo
> -        $OUT .= "access_log daemon:/var/log/squid/access.log squid\n";
So, please update the PR with the new patch.

2018-05-11 13:03 UTC, gsanchietti approved these changes

2018-05-14 15:01 UTC, merged